ifdef::backend-manpage[]
= qaj(1)
:doctype: manpage
:release-version: undefined
:man manual: User commands
:man source: quote-and-join {release-version}
:page-layout: base
:command: qaj

endif::[]
== NAME

qaj - quote and join words or lines in files

== SYNOPSIS

*qaj* [_OPTION_] [_FILE_]

== DESCRIPTION

*qaj* is a small utility to:

* select and sort items (words or lines) in files
* prefix and/or suffix items
* join the prefixed/suffixed items
* prefix and/or suffix the final result.

By default, the line selector is used and the items are trimmed.

With no FILE, or when FILE is `-`, read standard input.

== OPTIONS

=== Select and sort items

*-w*::
Select words.

*-l*::
Select lines.

*-s*::
Sort items in lexicographic order.

*-S*::
Sort items in reverse lexicographic order.

*-u*::
Remove duplicate items (implies *-s* or *-S* option).

=== Prefix and/or suffix items

*-q*::
Quote items with the character `'`.

*-qq*::
Quote items with the character `"`.

*-a* _string_::
Prefix each items with the given string.

*-b* _string_::
Suffix each items with the given string.

*-c* _string_::
Prefix and suffix each items with the given string.

*-p* _string_::
The given string must be `<`, `{`, `(` or `[`. Prefix each items with the given string. Suffix each items with the associated
closing parenthese of the given parenthese.

*-t*::
Do not trim item.

*-e*::
Do not escape parentheses in item.

=== Join the prefixed/suffixed items

*-j* _string_::
Use the given string to join quoted items.

*-J*::
Use the character `,` to join quoted items.

=== Prefix and/or suffix the final result

After the process of quoting, sorting and/or jointing:

*-A* _string_::
Prefix the result with the given string.

*-B* _string_::
Suffix the result with the given string.

*-C* _string_::
Prefix and suffix the result with the given string.

*-P* _string_::
The given parenthese must be `<`, `{`, `(` or `[`. Prefix the result with the given parenthese and suffix the result with
the associated closing parenthese.

include::qaj-examples.adoc[]

ifdef::backend-manpage[]
include::author.adoc[]
include::copyright.adoc[]
endif::[]