ifdef::backend-manpage[]
= qaj(1)
:doctype: manpage
:man manual: User commands
:man source: quote-and-join {release-version}
:page-layout: base
:command: qaj

== Name
endif::[]

qaj - quote and join words or lines in files

== SYNOPSIS

*qaj* [_OPTION_]... _FILE_...

== DESCRIPTION

qaj is a small utility which permits to extract items (words or lines) in files, apply a quote on items and then join
the quoted items.

== OPTIONS

=== Item selector

*-w*::
    Select words.

*-l*::
    Select lines.

=== Quote items

*-q*::
Quote items with the character ' (left & right).

*-qq*::
Quote items with the character " (left & right).

*-a* _string_::
Prefix each items with the given string.

*-b* _string_::
Suffix each items with the given string.

*-c* _string_::
Prefix and suffix each items with the given string.

*-p* _string_::
The given parenthese must be <, {, ( or [. Prefix each items with the given string. Uses the associated closing parenthese to
suffix each items.

*-t*::
Do not trim item.

*-e*::
Do not escape parentheses in item.

Sort:
    -s  sort
-S  sort in reverse order
-u  remove duplicate items (implies -s or -S option)

Join delimiter:
    -j  <string>
    -J  [ie , ]

After the process of quoting, sorting and/or jointing:
    -A <string>        append string to the left on the final result
-B <string>        append string to the right on the final result
-C <string>        append string to the left+right on the final result
-P <parenthese>    append parentheses to the left+right on the final result
the specified parenthese is the opening parenthese (<, {, ( or [)
    the right parenthese will be the closing parenthese

    FILE:

        With no FILE, or when FILE is -, read standard input.

== EXAMPLES

```example 1
$ echo lorem ipsum dolores est | qaj -w -q -j,
'lorem','ipsum','dolores','est'
```

```example 2
$ echo lorem ipsum dolores est | qaj -w -qq -j', '
"lorem", "ipsum", "dolores", "est"
```

```example 3
$ echo lorem ipsum dolores est | qaj -w -a'<' -b'>' -j# 
<lorem>#<ipsum>#<dolores>#<est>
```

```example 4
$ echo lorem ipsum dolores est | qaj -w
lorem
ipsum
dolores
est
```

```example 5
$ echo lorem ipsum dolores est | qaj -w -p'<' -j# 
<lorem>#<ipsum>#<dolores>#<est>
```

```example 6
$ printf "lorem\nipsum\n dolores\n\nest" | qaj -qq -j, 
"lorem","ipsum","dolores","est"
```

```example 7
$ printf "lorem\nipsum\n dolores\n\nest" | qaj -qq -J 
"lorem", "ipsum", "dolores", "est"
```

ifdef::backend-manpage[]
include::author.adoc[]
include::copyright.adoc[]
endif::[]
