ifdef::backend-manpage[]
= qaj(1)

== Name
endif::[]

qaj - qaj is a small utility to quote and join words or lines in files.

== SYNOPSIS

*qaj* [_OPTION_]... _FILE_...

== DESCRIPTION

Quote and join words or lines in FILE(s) to standard output.

With no FILE, or when FILE is -, read standard input.

*-a* _<string>_

    quote the left of word or line with the given string

*-A* _<string>_
    append string to the left on the final result

*-b* _<string>_
    quote the right of word or line with the given string

*-B* _<string>_
    append string to the right on the final result

*-c* _<string>_
    quote the left and right of word or line with the given string

*-C* _<string>_
    append string to the left+right on the final result

*-e*
    do not escape parentheses in item

*-j*  _<string>_
    join with the given string

*-J*
    join with the , character

*-l*
    select lines

*-p* _<parenthese>_
    quote the left and right of word or line with the given parenthese and its opposite parenthese

*-q*
    quote the left and right of word or line with the character '

*-qq*
    quote the left and right of word or line with the character "

*-s*
    sort

*-S*
    sort in reverse order

*-t*
    do not trim item

*-u*
    remove duplicate items (implies -s or -S option)

*-w*
    select words



== EXAMPLES

```example 1
$ echo lorem ipsum dolores est | qaj -w -q -j,
'lorem','ipsum','dolores','est'
```

```example 2
$ echo lorem ipsum dolores est | qaj -w -qq -j', '
"lorem", "ipsum", "dolores", "est"
```

```example 3
$ echo lorem ipsum dolores est | qaj -w -a'<' -b'>' -j# 
<lorem>#<ipsum>#<dolores>#<est>
```

```example 4
$ echo lorem ipsum dolores est | qaj -w
lorem
ipsum
dolores
est
```

```example 5
$ echo lorem ipsum dolores est | qaj -w -p'<' -j# 
<lorem>#<ipsum>#<dolores>#<est>
```

```example 6
$ printf "lorem\nipsum\n dolores\n\nest" | qaj -qq -j, 
"lorem","ipsum","dolores","est"
```

```example 7
$ printf "lorem\nipsum\n dolores\n\nest" | qaj -qq -J 
"lorem", "ipsum", "dolores", "est"
```

ifdef::backend-manpage[]
== AUTHOR

Written by Jean-François Giraud.

== COPYRIGHT

Copyright © 2020 Jean-François Giraud.  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
endif::[]
