ifdef::backend-manpage[]
= uqaj(1)
:doctype: manpage
:release-version: undefined
:man manual: User commands
:man source: quote-and-join {release-version}
:page-layout: base
:command: uqaj

endif::[]
== NAME

uqaj - split and unquote lines in files

== SYNOPSIS

*uqaj* [_OPTION_]... [_FILE_]...

== DESCRIPTION

Split and unquote lines in files

With no FILE, or when FILE is `-`, read standard input.

== OPTIONS

=== Unquoting

*-q*::
Unquote items with the character `'`

*-qq*::
Unquote items with the character `"`

*-a* _string_::
Remove prefix specified by string

*-b* _string_::
Remove suffix specified by string

*-c* _string_::
Remove prefix and suffix specified by string

*-p* _string_::
The given string must be `<`, `{`, `(` or `[`. Remove the given parenthese and associated closing parenthese of each items.

=== Splitting

*-j* _string_::
Split using the given string

*-J*::
Split using the character `,`

=== Before the process of splitting and unquoting

*-A* _string_::
Remove prefix specified by string

*-B* _string_::
Remove suffix specified by string

*-C* _string_::
Remove prefix and suffix specified by string

*-P* _string_::
Remove prefix (parenthese is `<`, `{`, `(` or `[`) and suffix (associated parenthese).

include::uqaj-examples.adoc[]

ifdef::backend-manpage[]
include::author.adoc[]
include::copyright.adoc[]
endif::[]